### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by timtim17** [FRC-1294/CiDemo#1]
Trying to File → Import → Gradle Project in Eclipse or trying to run `gradlew` with any task causes an error.

![d](https://cloud.githubusercontent.com/assets/6354860/10669495/dfd3e490-7895-11e5-8d9c-dff0eddbb5f8.PNG)

```
Trying to override old definition of datatype scp
Trying to override old definition of datatype sshexec

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\s-ajenchi\Desktop\CiDemo-master\build.gradle' line: 60

* What went wrong:
A problem occurred evaluating root project 'CiDemo-master'.
> repository not found: C:\Users\s-ajenchi\Desktop\CiDemo-master

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 25.235 secs
```

**Comment by JohnRudolfLewis** [comment]
I believe this is caused by not having a command line git available. (Evidence, on a mac with command line git in the path, the problem is not reproducible) I will be working to resolve this.

**Comment by timtim17** [comment]
Well, your last build just failed due to an error...

**Comment by timtim17** [comment]
It seems to have worked after 0c9c7fbc034cb1594473516b97f1fb652897799d. Thanks! :+1:
